import Quest from '../../../models/quest';
const tasks = [
  {
    name: 'Reading Time!',
    description: 'Choose a book!',
    completionExp: 10,
    index: 1,
    day: 1
  },
  {
    name: 'Reading Time!',
    description: 'Read your first 10 pages!',
    completionExp: 10,
    index: 2,
    day: 2
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 3,
    day: 3
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 4,
    day: 4
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 5,
    day: 5
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 6,
    day: 6
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 7,
    day: 7
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 8,
    day: 8
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 9,
    day: 9
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 10,
    day: 10
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 11,
    day: 11,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 12,
    day: 12,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 13,
    day: 13,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 14,
    day: 14,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 15,
    day: 15,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 16,
    day: 16,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 17,
    day: 17,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 18,
    day: 18,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 19,
    day: 19,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 20,
    day: 20,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 21,
    day: 21,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 21,
    day: 21,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 22,
    day: 22,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 23,
    day: 23,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 24,
    day: 24,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 25,
    day: 25,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 26,
    day: 26,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 27,
    day: 27,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 28,
    day: 28,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 29,
    day: 29,
  },
  {
    name: 'Half way there!!',
    description: 'Keep going! you have read 300 pages',
    completionExp: 10,
    index: 30,
    day: 30,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 31,
    day: 31,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 32,
    day: 32,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 33,
    day: 33,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 34,
    day: 34,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 35,
    day: 35,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 36,
    day: 36,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 37,
    day: 37,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 38,
    day: 38,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 39,
    day: 39,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 40,
    day: 40,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 41,
    day: 41,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 42,
    day: 42,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 43,
    day: 43,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 44,
    day: 44,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 45,
    day: 45,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 46,
    day: 46,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 47,
    day: 47,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 48,
    day: 48,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 49,
    day: 49,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 50,
    day: 50,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 51,
    day: 51,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 52,
    day: 52,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 53,
    day: 53,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 54,
    day: 54,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 55,
    day: 55,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 56,
    day: 56,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 57,
    day: 57,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 58,
    day: 58,
  },
  {
    name: 'Reading Time!',
    description: '10 Pages more!',
    completionExp: 10,
    index: 59,
    day: 59,
  },
  {
    name: 'Congratulations!!!',
    description: 'You have accomplished the quest and have read 600 pages!!!!',
    completionExp: 10,
    index: 60,
    day: 60,
  },
];

const createReadingTasks = async (quest: Quest) => {
  for await (const task of tasks) {
    await quest.createTask(task)
  }
};

export default createReadingTasks;